### ISSUE TITLE
Cathy Expert Mode Crash Bug

### ISSUE THREAD

**Issue by ramby06** [bunfan/beat-banger-public#398] opened 2024-07-05 13:20 UTC
### Discord Tag

@ramby06

### Issue Description

Hello!

When playing on Cathy's level on Expert mode, the game is guaranteed to crash about halfway through. Other difficulty modes for Cathy's level are unaffected and do not crash. 

### OS

Windows

### Version

3.7

### What level or section is the scene present.

The issue is only present on expert mode for Cathy's gaemplay

**Comment by Stefan-Mitric** [comment] 2024-07-06 11:50
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-06 11:50 UTC
Labels: bug, duplicate, Windows
