### ISSUE TITLE
Bug: Pressing left left right right left left right right opens debug

### ISSUE THREAD

**Issue by Newcrominus** [bunfan/beat-banger-public#74] opened 2023-10-22 15:05 UTC
### What happened?

![1111](https://github.com/bunfan/beat-banger-public/assets/107784806/8ca97e36-7b34-4593-b5d3-1d4ddc39f7e7)

### Version

3.165 (Secret)

**Comment by komdog** [comment] 2023-10-22 15:33
That's not a bug but I'll make it harder to access.

**Comment by komdog** [comment] 2023-10-22 15:37
Should be fixed

**Closed by komdog** 2023-10-22 15:37 UTC
Labels: bug
