### ISSUE TITLE
Bug: Cum effects Vanish in Results Screen

### ISSUE THREAD

**Issue by Kerucloven** [bunfan/beat-banger-public#102] opened 2023-10-23 08:48 UTC
### Discord Tag

Kerucloven#0201

### What happened?

Description:
Cum effects disappear in Results Screen.

Repro Steps:
1. Launch Beat Banger [secret]
2. Play > Act 1: Audition > Cathy
3. Complete the level at any difficulty

Actual:
Cum effects will vanish once the Results Screen is displayed.

Expected:
Cum effects should be still be visible while in the Results Screen.

Repro Rate:
3/3

Notes:

https://github.com/bunfan/beat-banger-public/assets/117617817/87044a57-c969-4dc4-9db3-870dd5647bab

https://github.com/bunfan/beat-banger-public/assets/117617817/237e7d24-187c-4157-a3f1-23ee6721f2b0

### OS

Windows

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment] 2023-10-23 11:01
Climax video resets to beginning thumbnail at score result #80

**Comment by komdog** [comment] 2023-10-23 14:33
Duplicate of #80

**Closed by komdog** 2023-10-23 14:33 UTC
Labels: bug
