### ISSUE TITLE
Modding tool update = Lose finished  levels data

### ISSUE THREAD

**Issue by Wabbite** [bunfan/beat-banger-public#243] opened 2024-02-15 16:00 UTC
### Discord Tag

wavebit

### Issue Description

After the update for "modding tool", all the data of finishing the story levels gets lost.
I still have everything i got from the store, but have to play all the levels from 0. (don't want to image it having this issue when the game is ready with all the story) 
![1](https://github.com/bunfan/beat-banger-public/assets/26908680/4c2b9bf5-f0d9-4815-9a39-006b38148726)
![2](https://github.com/bunfan/beat-banger-public/assets/26908680/beb54b2b-245c-487b-a4b4-d584b92c94f0)

### OS

Windows

### Version

3.452 (Steam)

**Comment by 1MPexe** [comment] 2024-02-15 18:03
1. Press F2, type and enter "dev", then type "open save" and open the new window in either notepad or visual studio code.
2. Within your save file, under " [save] " search for "act_name". To the right of act_name should be "Act I: Audition", erase this and replace it with "Beat Banger: Vol.1" .
3. Save and reload beat banger, and your files should return.

**Comment by Stefan-Mitric** [comment] 2024-02-16 09:26
#232

**Comment by komdog** [comment] 2024-02-17 02:44
Duplicate of #232

**Closed by komdog** 2024-02-17 02:44 UTC
Labels: bug, duplicate, Windows
