### ISSUE TITLE
Bug: Mod Bugs

### ISSUE THREAD

**Issue by JackMoon19** [bunfan/beat-banger-public#94] opened 2023-10-22 21:15 UTC
### Discord Tag

@joaquinluna18

### What happened?

Sometimes, when I complete a mod, the game crashes. Some of the mods' music is muffled.  The score screen cuts off the ending scene on all the mods.

### OS

Windows

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment] 2023-10-23 11:36
Problems with mods #81

**Comment by komdog** [comment] 2023-10-23 15:49
Dupe of #81 probably

**Closed by komdog** 2023-10-23 15:49 UTC
Labels: bug
