### ISSUE TITLE
Game crashing during Cathy expert level

### ISSUE THREAD

**Issue by Vahlokzin** [bunfan/beat-banger-public#410] opened 2024-07-13 08:54 UTC
### Discord Tag

@vahlokzin

### Issue Description

Just as the tittle says, my game crashes quite often when I reach a certain part in the Cathy level (image attached).
![image_2024-07-13_104945133](https://github.com/user-attachments/assets/affaf9be-3332-4aae-b700-fa652059ec52)
I suspect it's because I'm holding either W or D for too long, or perhaps accidentally pressing one while the other is already being held

### OS

Windows

### Version

3.7

### Modifiers Enabled?

Hardcore

### What level or section is the scene present.

Cathy - Expert

**Comment by Stefan-Mitric** [comment] 2024-07-13 11:04
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-13 11:04 UTC
Labels: bug, duplicate, Windows
