### ISSUE TITLE
Gale small errors

### ISSUE THREAD

**Issue by Yungdeag** [bunfan/beat-banger-public#244] opened 2024-02-15 18:45 UTC
### Issue Description

Gale still seems to be missing her open_mouth moans, simply needs
"voice_bank": [{
"timestamp": 0.0,
"voice_paths": ["gale_open_moan_1.ogg", "gale_open_moan_2.ogg", "gale_open_moan_3.ogg", "gale_open_moan_4.ogg", "gale_open_moan_5.ogg"]
}, {
added to keyframes. 

Also seems to have feet cutoff during gale_pussyfuck

### OS

Windows

### Version

3.452 (Steam)

**Comment by Stefan-Mitric** [comment] 2024-02-16 08:32
#125

**Comment by komdog** [comment] 2024-02-17 15:02
Duplicate of #125

**Closed by komdog** 2024-02-17 15:02 UTC
Labels: bug, duplicate, Windows
