### ISSUE TITLE
Coommi

### ISSUE THREAD

**Issue by GOOppy23** [bunfan/beat-banger-public#178] opened 2023-11-10 07:44 UTC
### Discord Tag

coommori

### Issue Description

What happened to no fail mode Why isn't the story progressing especially the mod? Can it be fixed?

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment] 2023-11-11 16:09
Duplicate of #174

**Closed by Stefan-Mitric** 2023-11-11 16:09 UTC
Labels: bug

**Comment by komdog** [comment] 2023-11-11 17:28
#175
