### ISSUE TITLE
simultaneous button presses causes crash

### ISSUE THREAD

**Issue by TestboyRai** [bunfan/beat-banger-public#405] opened 2024-07-11 21:35 UTC
### Discord Tag

@Raidak

### Issue Description

Im not sure if this is the exact cause, but whenever i press two different buttons at the same time while playing a level the game seemingly crashes. This seems to happen when there is a hold note involve. since the hold note button often stays pressed as i hit the next note before i've had the chance to release it. 
This happened while playing Version 24w28b pretty consistently. I went back to the older steam version to try if it had the same issue. It did crash on me while playing Cathys level on a hold note, but i couldn't get the crash as consistently as i did in Version 24w28b.

### OS

Windows

### Version

3.7

### Modifiers Enabled?

none

### What level or section is the scene present.

Most levels with hold notes on Version 24w28b. Only the Cathy level made the game crash on the steam version with just a short amount of testing.

**Comment by Stefan-Mitric** [comment] 2024-07-12 14:47
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-12 14:47 UTC
Labels: bug, duplicate, Windows
