### ISSUE TITLE
My game close randomly

### ISSUE THREAD

**Issue by Szinak11** [bunfan/beat-banger-public#411] opened 2024-07-14 15:51 UTC
### Discord Tag

@szinak11

### Issue Description

i play whit a level and in the middle sometimes the game just close randomly this day my game closed like 10 times

### OS

Windows

### Version

3.7

### Modifiers Enabled?

i not used any mode

### What level or section is the scene present.

this happen whit me in every level even in mods too

**Comment by Szinak11** [comment] 2024-07-14 15:52
in modifiers enabled?   i wanted say i not used any modifier sorry

**Comment by Stefan-Mitric** [comment] 2024-07-14 16:21
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-14 16:21 UTC
Labels: bug, duplicate, Windows
