### ISSUE TITLE
Bug: Gallery IMG #7 not unlocking.

### ISSUE THREAD

**Issue by Jax-Drades** [bunfan/beat-banger-public#184] opened 2023-11-18 06:06 UTC
### Discord Tag

Jax Drades

### Issue Description

I've gotten gold bands on all of the hard levels for each released character, just got blue band for zoe (the section the pic's in) and still no unlock, am suspecting a bug.

![image](https://github.com/bunfan/beat-banger-public/assets/149213877/db812233-5390-483a-ad47-7eebf85f9819)
![image](https://github.com/bunfan/beat-banger-public/assets/149213877/a5d9fd02-211c-4fb3-a7e6-05838d29590b)
![image](https://github.com/bunfan/beat-banger-public/assets/149213877/a9f8eb11-6abe-4348-8569-a58fd08329e6)
![image](https://github.com/bunfan/beat-banger-public/assets/149213877/336695a3-0d72-4363-a16b-530d0dea71ff)
![image](https://github.com/bunfan/beat-banger-public/assets/149213877/ba2f25a8-6acd-49c3-9162-384a0a7e2925)

### OS

Windows

### Version

3.3x (Steam)

**Comment by Stefan-Mitric** [comment] 2023-11-18 07:31
It has an alternative method of unlocking, compared to the rest.
Duplicate of #173.

**Closed by Stefan-Mitric** 2023-11-18 07:31 UTC
Labels: bug
