### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Chameleonpot** [bunfan/beat-banger-public#406] opened 2024-07-12 00:17 UTC
### Issue Description

Everytime i hold 2 buttons at once, the game crashes. I have no clue what causes this.

### OS

Windows

### Version

3.7

### What level or section is the scene present.

I've only noticed it during cathy

**Comment by Stefan-Mitric** [comment] 2024-07-12 14:48
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-12 14:48 UTC
Labels: bug, duplicate, Windows
