### ISSUE TITLE
Few setting bugs

### ISSUE THREAD

**Issue by Sitanikerdus** [bunfan/beat-banger-public#1] opened 2023-05-25 12:54 UTC
Bug 1
Notes visually appearing as wrong characters

1. Go to **settings** and **change keybinds** (doesn't matter what you change it to)
2. **Don't apply the settings**, just close the menu
3. Start a stage/cutscene
4. Check if keybinds match with HUD

Notes should've either changed or stayed the same.

_Changing keybinds that way seems to affect everything else that shows keybinds._

Bug 2
Also I noticed that options in pause menu (while in a stage) don't scroll and can sometimes go off the screen.
![image](https://github.com/bunfan/beat-banger-public/assets/134609695/33e198e2-25f5-452e-888b-7052a1a14657)

Referring to the screenshot, it can be seen that the lowest option is a little offscreen and can't be seen properly.
Switching menu or stage seems to also affect it.
![image_2023-05-25_154101040](https://github.com/bunfan/beat-banger-public/assets/134609695/2a2d3b76-9e8a-44d4-adb6-4be4d71594ce)

Steps to reproduce
1. Start a stage
2. Pause and open **settings**
3. Switch between option tabs
4. See the menu shift a little
5. To make it shift more, change stage and repeat the previous steps.

Menu should have shown as it normally does

System information
 - OS: Windows 10
 - Version 2.891

**Comment by komdog** [comment] 2023-05-25 14:15
Thanks for letting me know I'll look into it right now! ✨

**Comment by komdog** [comment] 2023-05-25 19:18
**Bug one has been resolved.** ✨ The temporary keys to be applied went into an array from which the game pulled the labels. When setting key binds, all your changes are stored in a temporary array called `temp_keys`. So the game only looks at the key binds you're setting once you hit the apply button.

**Comment by komdog** [comment] 2023-05-25 19:26
I cannot reproduce the second bug; it may have been fixed in a recent dev build. I'll push out an update to Steam in just a bit. Closing this issue for now, but if the options menu bug happens after the update, feel free to make a new issue.

**Closed by komdog** 2023-05-25 19:26 UTC
Labels: bug

**Comment by Sitanikerdus** [comment] 2023-05-25 20:21
That was fast! I'll be sure to let you know when something else comes up.
