### ISSUE TITLE
game crashing mid-game

### ISSUE THREAD

**Issue by nickelchin2000** [bunfan/beat-banger-public#396] opened 2024-07-04 22:03 UTC
### Discord Tag

chaossonic2010@gmail.com

### Issue Description

during the transition between long notes to a new key, the game will crash at the time and can't complete the level at all. please fix

### OS

Windows

### Version

3.7

### What level or section is the scene present.

expert mode and normal mode

**Comment by Stefan-Mitric** [comment] 2024-07-06 11:49
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-06 11:49 UTC
Labels: bug, duplicate, Windows
