### ISSUE TITLE
Crashing zone

### ISSUE THREAD

**Issue by Yajereti** [bunfan/beat-banger-public#407] opened 2024-07-12 04:13 UTC
### Discord Tag

@yajereti

### Issue Description

![20240711220412_1](https://github.com/user-attachments/assets/3add6039-d4d2-4847-bf54-b3e6ac9f267e)
Ok, so... it's in that exact part. at the first W, I have to stop hitting those or the game crash, I don't know if this has already passed or it's just me, I just.. well, I'm trying to get 100% and that crashing error it's my nemesis now

### OS

Windows

### Version

3.7

### Modifiers Enabled?

No Modifiers

### What level or section is the scene present.

Cathy gameplay at highest difficulty

**Comment by Stefan-Mitric** [comment] 2024-07-12 14:48
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-12 14:48 UTC
Labels: bug, duplicate, Windows
