### ISSUE TITLE
it crashes on expert mode

### ISSUE THREAD

**Issue by OrevTheAllay** [bunfan/beat-banger-public#401] opened 2024-07-09 15:20 UTC
### Issue Description

when i fail a bunch at hard mode when i retry it freezes and crashes instantly

### OS

Windows

### Version

3.7

### What level or section is the scene present.

any of the expert level

**Comment by Stefan-Mitric** [comment] 2024-07-11 16:41
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-11 16:41 UTC
Labels: bug, duplicate, Windows
