### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by triorez25** [bunfan/beat-banger-public#119] opened 2023-10-25 02:20 UTC
### Discord Tag

@triorez25b

### Issue Description

i completed Cathy on normal difficulty and the game crashed after the score screen

### OS

Windows

### Version

3.22 (Secret)

**Comment by DoodleSurf** [comment] 2023-10-25 05:42
Duplicate of #84

**Closed by DoodleSurf** 2023-10-25 05:42 UTC
Labels: bug
