### ISSUE TITLE
BB Bug

### ISSUE THREAD

**Issue by Kurolothgarian** [bunfan/beat-banger-public#393] opened 2024-07-04 04:49 UTC
### Issue Description

In Beat Banger during Cathy's Expert Mode, when the music goes to a 'hold C hold V rapid switch', the rapid pressing causes the game to crash.

### OS

Windows

### Version

3.7

### What level or section is the scene present.

Present in Cathy Expert Mode Gameplay

**Comment by Stefan-Mitric** [comment] 2024-07-04 20:02
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-04 20:02 UTC
Labels: bug, duplicate, Windows
