### ISSUE TITLE
Came crashes on startup

### ISSUE THREAD

**Issue by TrooperEddie** [bunfan/beat-banger-public#181] opened 2023-11-12 13:21 UTC
### Discord Tag

preacher1785

### Issue Description

Just downloaded the game in steam, crashes on startup :(

### OS

Windows

### Version

3.3

### Relevant log output

```shell
https://pastebin.com/xfSc1zP6
```

**Comment by Stefan-Mitric** [comment] 2023-11-12 23:32
Duplicate of #172

**Closed by Stefan-Mitric** 2023-11-12 23:32 UTC
Labels: bug, duplicate, MacOS
