### ISSUE TITLE
No Fail Mode issues and progression loss between versions, and weird after gale's song crash

### ISSUE THREAD

**Issue by DaringFlash** [bunfan/beat-banger-public#174] opened 2023-11-07 07:08 UTC
### Discord Tag

Daring_Flash#1948

### Issue Description

No fail mode no longer progresses the story and doesnt give you a score screen where in the previous version no fail mode still allowed story progression and to make for example expert modes not an instant fail if having combos like zvzczxz quickly after one another costing you more then the hearts you can max have. and another issue i lost all my progress (songs, gallery, star progression/ song completion, menu music) after the recent update without a prior warning. and final issue is yesterday i played gale's song and after i completed it and was on result screen for a like 2 second after pressing the confirm / mov on button the game weirdly automaticaly closed not taking me to the mission select screen or cutscene after ward just fully shut down

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment] 2023-11-07 14:13
The "No Fail" mode is designed to prevent progression within levels. The loss of your progression occurred due to the transition from Godot Engine 3 to 4. Also, we know about the game crash issue and are actively working to resolve it.
Duplicate of  #84

**Closed by Stefan-Mitric** 2023-11-07 14:13 UTC
Labels: bug, duplicate, Windows

**Comment by DaringFlash** [comment] 2023-11-11 15:16
stefan do you know that in past version it did allow progression

**Comment by Stefan-Mitric** [comment] 2023-11-11 16:07
Yes, it did, but Komdog has decided to change it.

**Comment by komdog** [comment] 2023-11-11 17:28
#175
