### ISSUE TITLE
animation Bug: finish scene

### ISSUE THREAD

**Issue by Splatspot** [bunfan/beat-banger-public#95] opened 2023-10-22 21:16 UTC
### Discord Tag

@Splatspot

### What happened?

you can see the final "vid" loop at the end of cathys level

### OS

Windows

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment] 2023-10-23 08:36
Does it loop forever?
Could you please create a video for us? It would greatly help in better understanding the process and validating the results. Thank you!

**Comment by komdog** [comment] 2023-10-23 14:48
Duplicate of bug #80

**Closed by komdog** 2023-10-23 14:48 UTC
Labels: bug
