### ISSUE TITLE
Game crashing on expert Virgin Newbie

### ISSUE THREAD

**Issue by FinnyBinnyBoo** [bunfan/beat-banger-public#373] opened 2024-06-20 17:09 UTC
### Discord Tag

@finnybinnyboo

### Issue Description

with the new update, right when you get to the section of Expert Virgin Newbie where you're alternating held V and C notes, the game really doesn't like that and crashes. I assume this is because of the held notes and potentially the little effect that pops when you hit a note, or it could possibly be because of holding down several keys in quick succession, but I have no solid answer.

### OS

Windows

### Version

3.7

### Modifiers Enabled?

None

### What level or section is the scene present.

Expert Virgin Newbie

**Comment by Stefan-Mitric** [comment] 2024-06-21 09:10
Duplicate of #349

**Closed by Stefan-Mitric** 2024-06-21 09:10 UTC
Labels: bug, duplicate, Windows
