### ISSUE TITLE
game crashes immediately when trying to launch from steam (mac os) 

### ISSUE THREAD

**Issue by hellowtimmy96** [bunfan/beat-banger-public#172] opened 2023-11-06 08:39 UTC
### Issue Description

Godot Engine v4.2.beta2.official.f8818f85e - https://godotengine.org
ERROR: Can't create an EGL display.
   at: _get_gldisplay_id (drivers/egl/egl_manager.cpp:60)
ERROR: Condition "gldisplay_id < 0" is true. Returning: ERR_CANT_CREATE
   at: window_create (drivers/egl/egl_manager.cpp:188)
ERROR: Can't create an OpenGL context.
   at: _create_window (platform/macos/display_server_macos.mm:196)
ERROR: Condition "main_window == INVALID_WINDOW_ID" is true.
   at: DisplayServerMacOS (platform/macos/display_server_macos.mm:4545)
zsh: segmentation fault  

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

### OS

Windows

### Version

3.3

### Relevant log output

```shell
Godot Engine v4.2.beta2.official.f8818f85e - https://godotengine.org
ERROR: Can't create an EGL display.
   at: _get_gldisplay_id (drivers/egl/egl_manager.cpp:60)
ERROR: Condition "gldisplay_id < 0" is true. Returning: ERR_CANT_CREATE
   at: window_create (drivers/egl/egl_manager.cpp:188)
ERROR: Can't create an OpenGL context.
   at: _create_window (platform/macos/display_server_macos.mm:196)
ERROR: Condition "main_window == INVALID_WINDOW_ID" is true.
   at: DisplayServerMacOS (platform/macos/display_server_macos.mm:4545)
zsh: segmentation fault  

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]
```

**Comment by Stefan-Mitric** [comment] 2023-11-06 10:13
Duplicate of #138

**Closed by Stefan-Mitric** 2023-11-06 10:13 UTC
Labels: bug, MacOS
