### ISSUE TITLE
Bug: Score Crash (Clare)

### ISSUE THREAD

**Issue by JackMoon19** [bunfan/beat-banger-public#79] opened 2023-10-22 15:20 UTC
### Discord Tag

@joaquinluna18

### What happened?

After completing Clare's level and getting my score, the game crashed. Luckily, the game still saved the score.

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment] 2023-10-23 09:12
Claire Level Crashing #84

**Comment by komdog** [comment] 2023-10-23 14:27
Dupe of fixed issue #84

**Closed by komdog** 2023-10-23 14:27 UTC
Labels: bug
