### ISSUE TITLE
Bug: Cutscene Crash (Gale)

### ISSUE THREAD

**Issue by JackMoon19** [bunfan/beat-banger-public#76] opened 2023-10-22 15:12 UTC
### Discord Tag

@joaquinluna18

### What happened?

The game crashed when I skipped the ending cutscene for Gale's level. 

### Version

3.165 (Secret)

### Relevant log output

```shell
It may have been because I skipped it too fast.
```

**Comment by Stefan-Mitric** [comment] 2023-10-23 09:12
Claire Level Crashing #84

**Comment by komdog** [comment] 2023-10-23 14:27
Dupe of fixed issue #84

**Closed by komdog** 2023-10-23 14:27 UTC
Labels: bug
