### ISSUE TITLE
Gale Animation Error

### ISSUE THREAD

**Issue by FlappyBoi032** [bunfan/beat-banger-public#350] opened 2024-06-03 23:47 UTC
### Issue Description

In the newest update for Beat Banger, in the Gale level her last animation phase doesn't load and stays on the current animation pose. Small error but I didn't see anyone posting about it on the Steam community page. Love the game btw!

### OS

MacOS

### Version

3.51

### What level or section is the scene present.

Present in final scene of Gale gameplay

**Comment by hackerTiger21** [comment] 2024-06-07 02:43
Duplicate of #347

**Closed** 2024-06-19 20:14 UTC
Labels: bug, Windows
