### ISSUE TITLE
Bug: The game closed after finishing Claire's level

### ISSUE THREAD

**Issue by SlatoAlt222** [bunfan/beat-banger-public#99] opened 2023-10-23 06:08 UTC
### Discord Tag

@slato222

### What happened?

The game automatically closed after clearing the Claire level on expert difficulty, I did a continuous playthrough from first level to last and had no modifiers.

After restarting the game, clearing Claire's level again on the conditions it did the expected and threw me in the "Work in progress" screen. Replaying the level multiple times sends you to that screen.

I couldn't replicate the problem after that.

### OS

Windows

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment] 2023-10-23 09:14
Claire Level Crashing #84

**Comment by komdog** [comment] 2023-10-23 14:27
Dupe of fixed issue #84

**Closed by komdog** 2023-10-23 14:27 UTC
Labels: bug
