### ISSUE TITLE
The game closes by hitting held buttons

### ISSUE THREAD

**Issue by Samambaia44** [bunfan/beat-banger-public#409] opened 2024-07-12 20:23 UTC
### Discord Tag

samambaia44

### Issue Description

Hello, I have a problem in the game, when we get to the notes where we have to hold down the button the game simply closes, in the first song it is impossible to get past the first notes with this problem, this happens with mods too, but in the old mods before they were added this mechanic of holding the button the game runs normally, thanks for your time and sorry for any kind of spelling mistakes, man, the English is terrible, so I had to use Google Translate :P

### OS

Windows

### Version

3.7

### Modifiers Enabled?

both

### What level or section is the scene present.

all

**Comment by Stefan-Mitric** [comment] 2024-07-13 11:04
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-13 11:04 UTC
Labels: bug, duplicate, Windows
