### ISSUE TITLE
Gale's code missing voice cue?

### ISSUE THREAD

**Issue by wildcard47** [bunfan/beat-banger-public#248] opened 2024-02-15 22:27 UTC
### Discord Tag

@wildcard47

### Issue Description

In the keyframes section of code, the "voicepaths" only uses the "gale_quick_moan" audios for the entire duration of the song, and does not use any of the "gale_open_moan" audios. I wasn't sure if this was intentional or not but thought I would bring it to yall's attention

### OS

Windows

### Version

3.452 (Steam)

**Comment by hackerTiger21** [comment] 2024-02-15 22:56
#244

**Comment by Stefan-Mitric** [comment] 2024-02-16 08:33
#125

**Comment by komdog** [comment] 2024-02-17 15:02
Duplicate of #125

**Closed by komdog** 2024-02-17 15:02 UTC
Labels: bug, duplicate, Windows
