### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by gazul5** [bunfan/beat-banger-public#100] opened 2023-10-23 06:22 UTC
### Discord Tag

gazul

### What happened?

the game crashed soon as i beat the second level on virgin (perfect score)
the instruction at 0x00007FF6D3568234 referenced memory at 0xFFFFFFFFFFFFFFFF, the memory could not be read.

### OS

Windows

### Version

3.165 (Secret)

**Comment by Stefan-Mitric** [comment] 2023-10-23 08:32
Can you provide the beatbanger.log file?

**Comment by Stefan-Mitric** [comment] 2023-10-23 09:14
Claire Level Crashing #84

**Comment by gazul5** [comment] 2023-10-23 14:08
> Could you please send me the 'beatbanger.log' file? Thanks!

sorry i didn't know how to do that at the time, and i had already gone to bed. but once i reopened the game the 3rd level was unlocked and i just kept playing and had no other problems.

**Comment by komdog** [comment] 2023-10-23 14:27
Dupe of fixed issue #84

**Closed by komdog** 2023-10-23 14:27 UTC
Labels: bug
