### ISSUE TITLE
Practice Mode

### ISSUE THREAD

**Issue by hackerTiger21** [bunfan/beat-banger-public#195] opened 2023-11-28 08:58 UTC
### Discord Tag

@atomicblaze21

### Describe the feature you would like

Include a secondary practice mode that allows a player to adjust the speed of the song up and down, as well as select a specific part of the chart to focus on repeatedly without having to reach it in the chart every single time. Any progress made in practice mode would be treated the same as progress in No Fail mode: no actual reward. A good example of such a practice system can be found in the rhythm game "A Dance of Fire and Ice".

### Additional context

This feature would be useful if someone wants to practice a particularly hard section of a chart without the stress of reaching the section over and over again, as well as allowing them to start slow and gradually speed up their execution of the rhythm sequence.

**Comment by hackerTiger21** [comment] 2023-11-30 01:59
Unknowingly submitted duplicate of #41, but with more context and an example. Will cross-reference this issue to the original.

**Comment by DoodleSurf** [comment] 2023-11-30 05:59
Duplicate of #41

**Closed by DoodleSurf** 2023-11-30 05:59 UTC
Labels: enhancement
