### ISSUE TITLE
Hidden notes

### ISSUE THREAD

**Issue by Jerico-4** [bunfan/beat-banger-public#250] opened 2024-02-16 02:45 UTC
### Discord Tag

jco4

### Issue Description

There are some mods I have downloaded that use notes that only show the color and outline of the note rather than the letter you need to press. Normally there's a dotted circle but it's just the color beacon now. Makes hitting the notes harder.

### OS

Windows

### Version

3.452 (Steam)

**Comment by DoodleSurf** [comment] 2024-02-17 10:45
Ghost notes appear invisible on controllers and seem to have no stylization from previous versions.
![image](https://github.com/bunfan/beat-banger-public/assets/133990496/68f9d0c3-d8cf-4026-9479-109878410a99)

**Comment by komdog** [comment] 2024-02-17 15:01
Duplicate of #249

**Closed by komdog** 2024-02-17 15:01 UTC
Labels: enhancement, Windows
