### ISSUE TITLE
Gale missing sex scene

### ISSUE THREAD

**Issue by hollowreyn** [bunfan/beat-banger-public#355] opened 2024-06-06 08:42 UTC
### Discord Tag

reyn.salas@gmail.com

### Issue Description

Gale's 4th sex scene is missing, it just stays on the third sex scene, until climax

### OS

Windows

### Version

3.51

### What level or section is the scene present.

present in Gale's gameplay

**Comment by hackerTiger21** [comment] 2024-06-07 02:43
Duplicate of #347

**Closed** 2024-06-11 17:48 UTC
Labels: bug, Windows
