### ISSUE TITLE
Game creash at specific notes

### ISSUE THREAD

**Issue by StaticObject-a** [bunfan/beat-banger-public#403] opened 2024-07-10 19:18 UTC
### Discord Tag

@el.gorbino

### Issue Description

I've been trying to beat Cathy's level on Expert without missing a single beat, but my game often crashes when I reach the 227th note on that level, it doesn't happen every time I play the level but it's the only time I ever crash

more info: https://steamcommunity.com/app/1813430/discussions/0/4408543731838697732/
that steam issue wasn't written by me but is vey relevant as this is not an isolated issue

### OS

Windows

### Version

3.7

### Modifiers Enabled?

no

### What level or section is the scene present.

first two

**Comment by Stefan-Mitric** [comment] 2024-07-11 16:40
Duplicate of #349

**Closed by Stefan-Mitric** 2024-07-11 16:40 UTC
Labels: bug, duplicate, Windows
