### ISSUE TITLE
Bug: Game Crashed After Zoe's Level

### ISSUE THREAD

**Issue by AlexBitHungary** [bunfan/beat-banger-public#77] opened 2023-10-22 15:12 UTC
### Discord Tag

@toxicgamer1132

### What happened?

I tried the beat banger beta("secret",Steam version),and after i beat zoe's level on normal,the game crashed(Or it closed itself),after a relaunch,i saw,i got the points from zoe's level,and the next level is unlocked.

### Version

3.165 (Secret)

**Comment by komdog** [comment] 2023-10-22 15:46
Could you add you logs? You can access them by pressing `F2` and entering the command `open logs`

**Comment by komdog** [comment] 2023-10-22 15:50
Actually just spam `up` and `down` til a debug menu appears and take a screenshot

**Comment by AlexBitHungary** [comment] 2023-10-22 16:38
Here's all of my logs(from the BETA version of the game).I hope it's going to help.There's 2 that seems to be a log about normal gameplay,and one of them was made during the session when i crashed.(I hope the logs gonna help,if there's no information about the crash in the logs,the game might was not able to save the info about it)

[beatbanger2023-10-22T16.57.11.log](https://github.com/bunfan/beat-banger-public/files/13063922/beatbanger2023-10-22T16.57.11.log)
[beatbanger2023-10-22T16.57.31.log](https://github.com/bunfan/beat-banger-public/files/13063923/beatbanger2023-10-22T16.57.31.log)
[beatbanger2023-10-22T17.09.12.log](https://github.com/bunfan/beat-banger-public/files/13063924/beatbanger2023-10-22T17.09.12.log)

**Comment by Stefan-Mitric** [comment] 2023-10-23 10:38
Claire Level Crashing #84

**Comment by komdog** [comment] 2023-10-23 14:27
Dupe of fixed issue #84

**Closed by komdog** 2023-10-23 14:27 UTC
Labels: bug
