### ISSUE TITLE
Game record gone

### ISSUE THREAD

**Issue by TBKUN** [bunfan/beat-banger-public#254] opened 2024-02-16 20:43 UTC
### Discord Tag

@tb_kun1005

### Issue Description

Every time after a new update launched, all the level just reset their record , all gone .only the game level have this problems , galleries, theater, music, shop didn't effect by the bug, but I have to play all the level again.

This bug have been happening to me all the time just this is better than last times since only the level got reset , last time the whole game reset all gone. I have seen someone happened the same problem with me and I dont know how to correct it.

The legacy version and Demo version already deleted , only steam version downloaded

Please solve this bug

### OS

Windows

### Version

3.452 (Steam)

**Comment by komdog** [comment] 2024-02-17 02:43
Duplicate of #232

**Closed by komdog** 2024-02-17 02:43 UTC
Labels: bug
