### ISSUE TITLE
Ending scene ending too early, making it repeat for less than a sec

### ISSUE THREAD

**Issue by FurSora** [bunfan/beat-banger-public#122] opened 2023-10-25 15:32 UTC
### Discord Tag

FurSora

### Issue Description

i notice when you finish the level the final animation plays fine but the second before ending ir just reset to the first second

### OS

Windows

### Version

3.3

**Comment by komdog** [comment] 2023-10-25 15:34
Dupe of issue #80

**Closed by komdog** 2023-10-25 15:34 UTC
Labels: bug
