### ISSUE TITLE
Game crash(?) or Freeze

### ISSUE THREAD

**Issue by Gabrielreda** [bunfan/beat-banger-public#372] opened 2024-06-20 03:12 UTC
### Discord Tag

@Gabrielreda

### Issue Description

Im playing the game normally and during a song the game will crash (in normal gameplay i didn't test mods) this started happening during the long notes update i think

### OS

Windows

### Version

3.7

**Comment by Stefan-Mitric** [comment] 2024-06-20 08:20
Duplicate of #349

**Closed by Stefan-Mitric** 2024-06-20 08:20 UTC
Labels: bug, duplicate, Windows
