### ISSUE TITLE
Sound bug

### ISSUE THREAD

**Issue by Bugcrunchr94** [bunfan/beat-banger-public#394] opened 2024-07-04 07:22 UTC
### Discord Tag

Tkdmasterjb

### Issue Description

When finishing a level if you miss or fail last note in a song the following cutscene will sound distorted 

### OS

Windows

### Version

3.7

### Modifiers Enabled?

None

### What level or section is the scene present.

All levels played

**Comment by Stefan-Mitric** [comment] 2024-07-04 20:02
Duplicate of #346

**Closed by Stefan-Mitric** 2024-07-04 20:02 UTC
Labels: bug, duplicate, Windows
